apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "start-smart-backend"
        metrics_path: /metrics
        static_configs:
          - targets:
              - backend.start-smart.svc.cluster.local:3000
            labels:
              service: "nest-backend"
              namespace: "start-smart"
