sonar.projectKey=start-smart-frontend
sonar.projectName=StartSmart Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/coverage/**

# karma.conf.js: coverage/frontend + lcov reporter
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.typescript.lcov.reportPaths=coverage/frontend/lcov.info
