apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app: ai-service
    part-of: start-smart
spec:
  type: ClusterIP
  selector:
    app: ai-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
