import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-final-feedback',
  template: `
    <div class="relative mt-8 bg-white/10 backdrop-blur-md rounded-2xl p-6 border border-white/20 shadow-xl overflow-hidden text-left group">
      <div class="absolute -top-4 -right-4 w-24 h-24 bg-blue-500/10 rounded-full blur-2xl group-hover:bg-blue-500/20 transition-all duration-700"></div>
      
      <div class="flex items-center gap-3 mb-4">
        <div class="w-10 h-10 rounded-full bg-gradient-to-br from-blue-400 to-indigo-600 flex items-center justify-center text-xl shadow-lg shadow-blue-500/20">
          🤖
        </div>
        <div>
          <h3 class="text-white font-black uppercase text-xs tracking-widest">AI Performance Review</h3>
          <div class="flex items-center gap-1.5">
            <span class="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse"></span>
            <span class="text-[10px] text-green-400 font-bold uppercase">RAG Analysis Active</span>
          </div>
        </div>
      </div>

      <p class="text-blue-50/90 text-sm italic leading-relaxed relative z-10">
        "{{ feedback }}"
      </p>

      <div class="mt-4 pt-4 border-t border-white/10 flex justify-between items-center">
        <span class="text-[9px] text-white/30 font-black uppercase tracking-tighter">Generated by StartSmart BrainRush Engine</span>
        <div class="flex gap-1">
          <span class="w-1 h-1 rounded-full bg-white/20"></span>
          <span class="w-1 h-1 rounded-full bg-white/20"></span>
          <span class="w-1 h-1 rounded-full bg-white/20"></span>
        </div>
      </div>
    </div>
  `
})
export class FinalFeedbackComponent {
  @Input() feedback = 'Analyse de votre performance en cours...';
}
